version: 0.0
os: linux
files:
  - source: /
    destination: /home/centos/simplereact
hooks:
  AfterInstall:
    - location: scripts/pre.sh
      timeout: 200
      runas: centos
  ApplicationStart:
    - location: scripts/post.sh
      runas: centos